
var plural = require('./plural');

/**
 * [toModel simple json to model sails]
 * @param  {[type]} model_basic [description]
 * @return {[string]}             [string]
 */
exports.toModel = function(model_basic) {
	var out = [];
	out.push("/**");
	out.push("\tGenerated by sails-inverse-model");
	out.push("\tDate:" + (new Date()));
	out.push("*/\n");
	out.push("module.exports = {");
	out.push(model_basic);
	out.push("};");
	return out.join("\n");
}

exports.saveController = function(name, plurallang) {
	var content = [];
	content.push("/**");
	content.push("* " + name);
	content.push("*");
	content.push("* @description :: Server-side logic for managing " + name);
	content.push("* @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers");
	content.push("*/");
	content.push("module.exports = {");
	content.push("");
	content.push("};");
  return content.join("\n");
}

exports.capitalize = function(word) {
	return word.replace(/(^|\s)([a-z])/g, function(m, p1, p2) {
		return p1 + p2.toUpperCase();
	})
}
