/**
 * to.js
 * @autor Julian David (@anlijudavid)
 * @version 1.0.0
 * 2016
 */

var plural = require('./plural');
var to = require('../configs/to');

/**
 * [toModel simple json to model sails]
 * @param  {[type]} model_basic [description]
 * @return {[string]}             [string]
 */
exports.toModel = function(model_basic) {
	var out = [];
	out.push("/**");
	out.push("\tGenerated by sails-inverse-model");
	out.push("\tDate:" + (new Date()));
	out.push("*/\n");
	out.push("module.exports = {");
	out.push(model_basic);
	out.push("};");
	return out.join("\n");
}

exports.saveController = function(name, plurallang) {
	return [
		"/**",
		"* " + name,
		"*",
		"* @description :: Server-side logic for managing " + name,
		"* @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers",
		"*/",
		"module.exports = {",
		"index: function(req, res, next) {",
		"	" + exports.capitalize(name) + ".find().exec(function(err, list) {",
		"		if (err) return Error('Error');",
		"		console.log('Mostrando comandos');",
		"		return res.view({",
		"			result: list",
		"		});",
		"	});",
		"}",
		"",
		"};"
	].join("\n");
}

exports.capitalize = function(word) {
	return word.replace(/(^|\s)([a-z])/g, function(m, p1, p2) {
		return p1 + p2.toUpperCase();
	})
}
